name: Binance AI Bot 7/24

on:
  schedule:
    # Bu ayar botu her 15 dakikada bir otomatik çalıştırır
    - cron: '*/15 * * * *'
  workflow_dispatch: # İstediğinde elle başlatabilmen için

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Kodları Çek
        uses: actions/checkout@v3

      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Kütüphaneleri Yükle
        run: pip install -r requirements.txt

      - name: Botu Çalıştır
        run: python main.py
